<?php
/**
 * @file nyc_picture_demo.module
 * 
 * @author Shawn P. Duncan <shawn@c3design.org>
 * @date   4/3/14,  11:33 AM
 *
 *
 * Copyright 2014 by Shawn P. Duncan.  This code is
 * released under the GNU General Public License.
 * Which means that it is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
 * */

/* Implementation of hook_views_api code in nyc_ref_demo.views.inc
 * will now be auto loaded
 * */
function nyc_picture_demo_views_api() {
  return array(
    'api' => '3.0'
  );
}